
[font]
size = 10

[font.bold]
family = "GeistMono NFM"
style = "Bold"

[font.bold_italic]
family = "GeistMono NFM"
style = "Bold Italic"

[font.italic]
family = "GeistMono NFM"
style = "Italic"

[font.normal]
family = "GeistMono NFM"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

