icons_format = "{icon}"

[theme]
theme = "space-villain"
[theme.overrides]
idle_bg = "#0d0c0c"
idle_fg = "#c8c093"
good_bg = "#181616"
good_fg = "#c8c093"
warning_bg = "#625263"
warning_fg = "#c8c093"
critical_bg =  "#c4746e"
critical_fg = "#f8f0c3"
info_bg = "#4e6462"
info_fg = "#c8c093"

[icons]
icons = "awesome4"

[[block]]
block = "focused_window"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "


[[block]]
block = "net"
format = "$icon $ssid ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "temperature"

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "packages"
aur_command = "paru -Qua"
format_up_to_date = ""
